version : "3"

# configs:
#   prometheus_config:
#     file: ./prometheus.yml

networks:
  dotnetcorepromgrafana:
 
services:
  promgrafmetrics:
    image: promgrafmetrics
    restart: always
    ports:
      - 8082:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
    networks:
      - dotnetcorepromgrafana

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    # configs:
    #   - source: prometheus_config
    #     target: /etc/prometheus/prometheus.yml
    depends_on:
      - promgrafmetrics
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api' 
    networks:
      - dotnetcorepromgrafana
   

  grafana: 
    image: grafana/grafana
    depends_on: 
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=a
    restart: always
    # volumes:
    #   - ./grafana/data/:/var/lib/grafana
    #   - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    networks:
      - dotnetcorepromgrafana

